sudo: required
services:
  - docker

before_install:
  - docker build -t keiju/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true keiju/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-east-1"
  app: "docker"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-us-east-1-743731135206
  bucket_path: "docker"
  on:
    branch: master
